### ISSUE TITLE
A couple of small changes to readme.md

### ISSUE THREAD

**Issue by richardhuf84** [willianjusten/bootstrap-boilerplate#1]
Hi willianjusten,

thanks for this repo! I just wanted to suggest 2 small errors in the readme:
1. it says:

```
# Clone this repository
$ git clone git://github.com/willianjusten/bootstrap-boilerplate.git new_project
$ cd new_project

# install dependencies
$ npm install
```

Should this be

```
$ cd /bootstrap-boilerplate
$ npm install
```
1. inicialize -> initialize.

I hope you don't mind these suggestions. Thanks again for the great repo!

**Comment by willianjusten** [comment]
Hi @richardhuf84, 

thanks for your tips.
- When you put "new_project" or something else after the "git clone repo", a folder will be created with the chosen name. I think it's better than "bootstrap-boilerplate", don't you think?
- If you use "cd /bootstrap-boilerplate", you'll get an error, 
  "-bash: cd: /boostrap-boilerplate: No such file or directory", because you don't have any folder with this name at " / " directory.
- Thanks for "initialize", was a typo =)

**Comment by richardhuf84** [comment]
Hi @willianjusten 

Thanks. My apologies, you're correct. Thanks again. I'll close this issue.

🙏
